language: node_js
branches:
  only:
   - master
before_install:
  - npm i yarn -g
script:
  - yarn
  # - yarn create-ratings
  - yarn build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  on:
    branch: master